// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACaMSkpOKvY4adoQ_cdVgT7XRwQ2cwjI8',
    appId: '1:19600582432:web:d61c7bbcfb42f3a7605945',
    messagingSenderId: '19600582432',
    projectId: 'canteexpress',
    authDomain: 'canteexpress.firebaseapp.com',
    storageBucket: 'canteexpress.appspot.com',
    measurementId: 'G-2WY389CMZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw4Q4DSIiqJPrkaYORUbg-AOXYlT79E-Q',
    appId: '1:19600582432:android:e34d8188cdff6424605945',
    messagingSenderId: '19600582432',
    projectId: 'canteexpress',
    storageBucket: 'canteexpress.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_XnvAw9aMP7cxvoexc2ZMC9EEM62-nLU',
    appId: '1:19600582432:ios:9f01f07e196d5a39605945',
    messagingSenderId: '19600582432',
    projectId: 'canteexpress',
    storageBucket: 'canteexpress.appspot.com',
    androidClientId: '19600582432-h04b987m8fh8ut9p87l5deb4reb6drj9.apps.googleusercontent.com',
    iosClientId: '19600582432-7voe0e24an1rgke82255l4jo4l35q2oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineFoodOrderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_XnvAw9aMP7cxvoexc2ZMC9EEM62-nLU',
    appId: '1:19600582432:ios:ab452cc0618a793a605945',
    messagingSenderId: '19600582432',
    projectId: 'canteexpress',
    storageBucket: 'canteexpress.appspot.com',
    androidClientId: '19600582432-h04b987m8fh8ut9p87l5deb4reb6drj9.apps.googleusercontent.com',
    iosClientId: '19600582432-u6qaj1r991pg9p9be7fndip5ac4eiprt.apps.googleusercontent.com',
    iosBundleId: 'com.example.onlineFoodOrderApp.RunnerTests',
  );
}
